### ISSUE TITLE
inboxer-1.1.5 fails to start

### ISSUE THREAD

**Issue by jmarino** [denysdovhan/inboxer#72]
Inboxer-1.1.5 fails to start in my machine with the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/inboxer/node_modules/insight/node_modules/external-editor/main/index.js:15:10)
    at Object.<anonymous> (/usr/lib/inboxer/node_modules/insight/node_modules/external-editor/main/index.js:229:4)
    at Object.<anonymous> (/usr/lib/inboxer/node_modules/insight/node_modules/external-editor/main/index.js:231:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
```

Version 1.1.4 was working fine. This problem was introduced by commit 8310e21643b10123e60416e6ea341bc3713fc005, which updated dependency package insight to version 0.10.1. Reverting to version insight-0.8.4 fixes the problem for me.

**Comment by jonatandorozco** [comment]
I'm going to check it

**Comment by jonatandorozco** [comment]
I checked it on Xubuntu 18.04 and Windows 10, I have no problem with 1.1.5 version. What's your OS?

**Comment by jmarino** [comment]
Sorry, I should have provided more details about my system. 
I'm running ArchLinux with these packages:
electron 2.0.8
nodejs 10.10.0
semver 5.5.1
node-gyp 3.8.0
npm 6.4.1

**Comment by jonatandorozco** [comment]
Thanks @jmarino ,

I'm going to check in order to get it fixed. Could you help me doing tests after changes?

**Comment by jmarino** [comment]
Sure, let me know what I can test.

When I was trying to figure this out myself I noticed that in version 1.1.4, file `package-lock.json` had only one reference to package `tmp` as a dependency, to `tmp-0.0.33`.

In version 1.1.5, file `package-lock.json` has more references to package `tmp`, one to `tmp-0.0.28` and several to `tmp-0.0.33`.

**Comment by jonatandorozco** [comment]
@jmarino 

Check these install files

https://drive.google.com/file/d/1-7rcUcYBonF1kzUrvpHvr9byH-ZVSWKt/view?usp=sharing

Let me know how was it

**Comment by cralor** [comment]
![image](https://user-images.githubusercontent.com/138880/45329334-81bf1080-b525-11e8-84cb-3d9338e71b2b.png)

I'm getting this now w/ 1.1.5 "upgraded"... related? I uninstalled too.

**Comment by jmarino** [comment]
I downloaded your dist1.1.6. Inside I found a .deb package and a .AppImage. I was able to run the AppImage file and it worked as expected, no problems. I was not able to do anything with the .deb file.

I looked inside the .deb file and the .AppImage and things look very different from my local installation here. The way inboxer gets installed in my system is by running `npm install --production` as shown in the [package's build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=inboxer). Perhaps we're installing things wrong in ArchLinux? I confess I don't know much about electron apps.

**Comment by jonatandorozco** [comment]
Hi @cralor ,

I'm going to make a build for Windows, so Can you check it?

**Comment by jonatandorozco** [comment]
@jmarino Would you like using the .deb instead of .AppImage? I'm a newbie at linux. I'm going to install your distro in order to test the app.

**Comment by jmarino** [comment]
Wow, that sounds a bit overkill @jonorozcoc.
I can't use the .deb file because that's a package for debian related linux distros. I prefer not to use the self contained AppImage because it comes bundled with libraries and stuff that I already have in my system, plus it has to extract itself everytime it's run.

Before you go down the ArchLinux rabbit hole let me explore more closely what's inside the .AppImage file and see if I can figure anything out. I used `--appimage-extract` to extract the contents of the .AppImage and I see that the app is packed as an .asar package. I'll look inside and see how it differs from my local installation.

**Comment by jmarino** [comment]
I extracted the contents of the .AppImage you sent me:
`./inboxer-1.1.6-beta1-x86_64.AppImage --appimage-extract`

Then I extracted the contents of the `squashfs-root/resources/app.asar` file and looked at the `package.json` file, which has this section:
```
"dependencies": {
    "electron-context-menu": "^0.9.1",
    "electron-dl": "^1.10.0",
    "electron-is-dev": "^0.3.0",
    "electron-log": "^2.2.11",
    "electron-store": "^1.3.0",
    "electron-updater": "^3.0.3",
    "first-run": "^1.2.0",
    "insight": "^0.8.4",
    "minimatch-all": "^1.1.0"
  }
```
That looks a lot like the 1.1.4 version. Indeed, the version requested for the dependency `insight` is 0.8.4 (like Inboxer-1.1.4) instead of 0.10.1 (like Inboxer-1.1.5). So it's no wonder this AppImage worked for me, it uses the older version of package `insight`.

In case you can't extract the .asar file, you can look inside it without having to extract it:
```grep -a -A27 '1.1.6-beta1' squashfs-root/resources/app.asar```

The command above shows a partial dump of the file `package.json` file from Inboxer.

**Comment by jonatandorozco** [comment]
Ok, I'm taking a look on Arch package are made in order to update inboxer package

**Comment by jmarino** [comment]
It looks like you're building version 1.1.4 by mistake. Maybe you didn't
sync your local repo and are applying your changes on top of 1.1.4 instead
of 1.1.5.
Send me an AppImage of plain 1.1.5 and I'll test it.

**Comment by jmarino** [comment]
Well, that was a dumb request on my part. I can go ahead and download the 1.1.5 AppImage myself from the release page.

So I did that, and I can confirm that the 1.1.5 AppImage works fine in my machine. So I only have the problem when I run a local build of inboxer-1.1.5. I'll try to get more info about what's different between my local build and the official one.

**Comment by jmarino** [comment]
Alright, I figured it out. As expected it's not a bug in inboxer but a bug in the ArchLinux package. As part of the packaging process it was deleting the `node_modules/tmp` folder where the `tmp` package was installed. D'oh!
